//
//  DefaultContent.swift
//  TruthOrDare
//
//  Created by Imran Hajiyev on 10.08.23.
//

struct DefaultContent {
    let truthPool: [String] = [
        "What is your biggest fear?",
        "What is the most embarrassing photo of you?",
        "What’s your biggest regret?",
        "Who do you have a crush on?",
        "Who is the best-looking person here?",
        "Who is the funniest person here?",
        "What is the strangest dream you’ve ever had?",
        "Who was your first kiss?",
        "Have you ever shared a secret you weren’t supposed to tell?",
        "What are your thoughts on reincarnation?",
        "Have you ever been arrested?",
        "Which is the place that you want to travel to the most?",
        "What’s the best lie you’ve ever told anyone to your ex?",
        "Would you marry a sugar daddy even was much older than you?",
        "Who in this room do you trust the least and who the most?",
        "What’s the meanest thing you’ve ever said about someone else?",
        "Who are you most jealous of?",
        "What was your biggest childhood fear?",
        "Would you date your first love today?",
        "Do you believe in aliens?",
        "Which one movie is your guilty pleasure?",
        "What is the last message you sent to your best friend?",
        "What’s the last time you threw up from drinking too much?",
        "If you were guaranteed to never get caught, who would you murder?",
        "Have you ever had a profile in a dating app?",
        "What is the worst food you’ve ever tasted?",
        "Have you ever broken an expensive item in a store and then leave?",
        "If you had to delete one app from your phone, which one would it be?",
        "What’s the longest you’ve gone without sex?",
        "Have you ever used a fake ID?",
        "Have you ever smoked weed?",
        "What is your greatest fear in a relationship?",
        "Do you sing in the shower?",
        "What’s the longest you’ve gone without brushing your teeth?",
        "Who would you hate to see naked?",
        "Have you ever sent a sexting message to the wrong person?",
        "Would you break up with your partner for $1 million?",
        "Have you ever taken a sexy picture of yourself?",
        "Which one thing you don't like about everyone in the group?",
        "When’s the last time you texted your ex?",
        "If you had to pick another place to live, which is the place?"
    ]
    
    let darePool: [String] = [
        "Send a heart-eye emoji in response to your crush’s Instagram story.",
        "I dare you to order me $5 worth of food delivery.",
        "Dress up like me and send a photo.",
        "Tell us your most embarassing story.",
        "Tell the funniest story of how you met someone in the group.",
        "Do 10 sit-ups.",
        "Do 10 pushups.",
        "Write a love letter to someone in the group.",
        "Imitate your favorite emoji.",
        "Call one of your contacts and pretend to be a different personality.",
        "Describe the weirdest thing you’ve ever done while you were drunk.",
        "Make an animal sound.",
        "Perform a scene from your favorite show",
        "Show the last text that your ex sent to you.",
        "Pretend to be the person who is sitting right next to you.",
        "Post something very personal or weird on social media.",
        "Talk with a foreign accent for the remainder of the game.",
        "Let someone send a text message to any of your contacts using your phone.",
        "Give the group laugh therapy, and don’t stop until everybody’s cracked a smile.",
        "Sing the national anthem as if you were a cat or a dog.",
        "Let the group choose a word and a well-known song. You have to sing that song and insert that word in every line.",
        "Act like an animal for one minute. The group may shout out any animal, and as many animals, they like.",
        "Take an embarrassing selfie and post it as your profile picture.",
        "Fake cry every time you speak, for the remainder of the game.",
        "Say everything in rhyme for the rest of the game.",
        "Text your crush and tell him or her about your feelings.",
        "Silently do ‘The Macarena’.",
        "Tell the story of how you and your partner met in a robot voice.",
        "Pick up a random book and read one page out loud in a very seductive voice.",
        "Text someone using only your nose.",
        "Have a full conversation with a broom.",
        "Sing what you have to say instead of talking.",
        "Use a hairbrush as a microphone.",
        "Talk in the third person.",
        "Talk in a high-pitched voice.",
        "Do the chicken dance.",
        "Show us your screen time report",
        "Yell out the first word that comes to your mind",
        "Repeat everything the person on your right is saying until it’s your turn again",
        "Whisper a secret to the person on your left",
        "Say two honest things about everyone else in the group"
    ]
}
